name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses:
      ./.github/workflows/build.yml

  create-release-assets:
    name: Create release assets
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Merge build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ env.GITHUB_WORKSPACE }}/artifacts/stage
        merge-multiple: true

    - name: Create ZIP archive
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        Compress-Archive -Path ${{ env.GITHUB_WORKSPACE }}/artifacts/stage/* -DestinationPath ${{ env.GITHUB_WORKSPACE }}/artifacts/DXErr.zip

    - name: Upload release
      id: upload_release
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: DXErr
        path: |
          ${{ env.GITHUB_WORKSPACE }}/artifacts/stage/*
        if-no-files-found: error
        retention-days: 1

    - name: Get Current Release
      id: current_release
      uses: joutvhu/get-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        debug: true

    - name: Update release
      id: update_release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: shogo82148/actions-upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.current_release.outputs.upload_url }}
        asset_path: ${{ env.GITHUB_WORKSPACE }}/artifacts
        asset_name: DXErr.zip
        asset_content_type: application/zip
