name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses:
      ./.github/workflows/build.yml

  create-release-assets:
    name: Create release assets
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Merge build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{env.GITHUB_WORKSPACE}}/artifacts/stage
        merge-multiple: true

    - name: Create ZIP archive
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        Compress-Archive -Path ${{env.GITHUB_WORKSPACE}}/artifacts/stage/* -DestinationPath ${{env.GITHUB_WORKSPACE}}/artifacts/DXErr.zip

    - name: Update release
      id: update_release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: ${{env.GITHUB_WORKSPACE}}/artifacts/DXErr.zip

    - name: Upload release
      id: upload_release
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: DXErr
        path: |
          ${{env.GITHUB_WORKSPACE}}/artifacts/stage/*
        if-no-files-found: error
        retention-days: 1
